import { OrganizerData, TopLevelCategory } from './types';

export const ORGANIZER_DATA: OrganizerData[] = [
  { id: '1', mota: 'Hasiera', antolatzaileak: 'Lehenengo eta behin...', esanahia: 'Primero que nada...', adibidez: 'Lehenengo eta behin, eskerrak eman nahi dizkizuet.' },
  { id: '2', mota: 'Hasiera', antolatzaileak: 'Lehenik eta behin...', esanahia: 'Antes que nada...', adibidez: 'Lehenik eta behin, arauak azalduko ditut.' },
  { id: '3', mota: 'Hasiera', antolatzaileak: 'Lehen-lehenik...', esanahia: 'En primerísimo lugar...', adibidez: 'Lehen-lehenik, sarrera bat egingo dugu.' },
  { id: '4', mota: 'Hasiera', antolatzaileak: 'Ezer baino lehen...', esanahia: 'Antes de nada...', adibidez: 'Ezer baino lehen, kontuan hartu behar dugu testuingurua.' },
  { id: '5', mota: 'Hasiera', antolatzaileak: 'Hasteko...', esanahia: 'Para empezar...', adibidez: 'Hasteko, gai nagusia aurkeztuko dugu.' },
  { id: '6', mota: 'Hasiera', antolatzaileak: 'Hasteko, esan behar da...', esanahia: 'Para empezar, hay que decir...', adibidez: 'Hasteko, esan behar da egoera ez dela erraza.' },
  { id: '7', mota: 'Hasiera', antolatzaileak: 'Hasteko, esan dezadan...', esanahia: 'Para empezar, diré...', adibidez: 'Hasteko, esan dezadan pozik nagoela hemen egoteaz.' },
  { id: '8', mota: 'Hasiera', antolatzaileak: 'Hasiera batean...', esanahia: 'Al principio...', adibidez: 'Hasiera batean, dena nahasia zen.' },
  { id: '9', mota: 'Hasiera', antolatzaileak: 'Hasiera emateko...', esanahia: 'Para dar comienzo...', adibidez: 'Hasiera emateko, ikus dezagun zer gertatu den azken hilabetean.' },
  { id: '10', mota: 'Hasiera', antolatzaileak: 'Abiapuntu bezala...', esanahia: 'Como punto de partida...', adibidez: 'Abiapuntu bezala, erabiliko dugu datu estatistiko hau.' },
  { id: '11', mota: 'Hasiera', antolatzaileak: 'Gutun honen bidez...', esanahia: 'Mediante esta carta...', adibidez: 'Gutun honen bidez, nire kexa adierazi nahi dut.' },
  { id: '12', mota: 'Hasiera', antolatzaileak: 'Idazki honen bitartez...', esanahia: 'A través de este escrito...', adibidez: 'Idazki honen bitartez, nire iritzia plazaratu nahi dut.' },
  { id: '13', mota: 'Hasiera', antolatzaileak: 'Bazen behin...', esanahia: 'Érase una vez...', adibidez: 'Bazen behin herri txiki bat mendien artean.' },
  { id: '14', mota: 'Hasiera', antolatzaileak: 'Dena hasi zen...', esanahia: 'Todo comenzó...', adibidez: 'Dena hasi zen udako gau batean.' },
  { id: '15', mota: 'Hasiera', antolatzaileak: 'Hasiera batean...', esanahia: 'Al principio...', adibidez: 'Hasiera batean, ez genuen ulertzen zer gertatzen ari zen.' },
  { id: '16', mota: 'Jarraipena', antolatzaileak: 'Segidan...', esanahia: 'A continuación...', adibidez: 'Segidan, beste adibide bat ikusiko dugu.' },
  { id: '17', mota: 'Jarraipena', antolatzaileak: 'Jarraian...', esanahia: 'Seguidamente...', adibidez: 'Jarraian, galderak erantzungo ditugu.' },
  { id: '18', mota: 'Jarraipena', antolatzaileak: 'Honen ondoren...', esanahia: 'Después de esto...', adibidez: 'Honen ondoren, emaitzak aztertuko ditugu.' },
  { id: '19', mota: 'Jarraipena', antolatzaileak: 'Honen ostean...', esanahia: 'Tras esto...', adibidez: 'Honen ostean, ondorioetara helduko gara.' },
  { id: '20', mota: 'Jarraipena', antolatzaileak: 'Hori(ek) horrela...', esanahia: 'Así las cosas...', adibidez: 'Horiek horrela, erabakia hartzea erraza da.' },
  { id: '21', mota: 'Jarraipena', antolatzaileak: 'Are gehiago...', esanahia: 'Además...', adibidez: 'Are gehiago, aurrekontua ere handitu da.' },
  { id: '22', mota: 'Jarraipena', antolatzaileak: 'Ildo (hari) berean...', esanahia: 'En la misma línea...', adibidez: 'Ildo berean, beste ekimen bat jarri dute martxan.' },
  { id: '23', mota: 'Jarraipena', antolatzaileak: 'Ildo (hari) beretik...', esanahia: 'En la misma línea...', adibidez: 'Ildo beretik, antzeko erabakiak hartu dira.' },
  { id: '24', mota: 'Jarraipena', antolatzaileak: 'Ildo (hari) berari jarraituz...', esanahia: 'Siguiendo esa línea...', adibidez: 'Ildo berari jarraituz, politika berriak ezarri dituzte.' },
  { id: '25', mota: 'Jarraipena', antolatzaileak: 'Horren ildo(tik) (haritik)...', esanahia: 'En esa línea...', adibidez: 'Horren ildo(tik), neurri berriak iragarri dira.' },
  { id: '26', mota: 'Jarraipena', antolatzaileak: 'Horrekin batera...', esanahia: 'Junto con eso...', adibidez: 'Horrekin batera, prestakuntza saioak egingo dira.' },
  { id: '27', mota: 'Jarraipena', antolatzaileak: 'Bestalde...', esanahia: 'Por otro lado...', adibidez: 'Bestalde, irakasleek prestakuntza jasoko dute.' },
  { id: '28', mota: 'Jarraipena', antolatzaileak: 'Beste alde batetik...', esanahia: 'Por otra parte...', adibidez: 'Beste alde batetik, ikasleek parte hartuko dute.' },
  { id: '29', mota: 'Jarraipena', antolatzaileak: 'Horrez gain...', esanahia: 'Además de eso...', adibidez: 'Horrez gain, laguntza ekonomikoa jasoko dute.' },
  { id: '30', mota: 'Jarraipena', antolatzaileak: 'Horretaz gainera...', esanahia: 'Aparte de eso...', adibidez: 'Horretaz gainera, etxebizitza bat ere eskuratu dute.' },
  { id: '31', mota: 'Jarraipena', antolatzaileak: 'Ez hori bakarrik...', esanahia: 'No solo eso...', adibidez: 'Ez hori bakarrik, baita laguntza teknikoa ere.' },
  { id: '32', mota: 'Jarraipena', antolatzaileak: 'Hori ez ezik... ere', esanahia: 'No solo eso, sino también...', adibidez: 'Hori ez ezik, prestakuntza-saioak ere eskainiko dira.' },
  { id: '33', mota: 'Jarraipena', antolatzaileak: 'Baita ere...', esanahia: 'También...', adibidez: 'Baita ikastaro osagarriak ere.' },
  { id: '34', mota: 'Jarraipena', antolatzaileak: 'Era berean...', esanahia: 'Del mismo modo...', adibidez: 'Era berean, ikastetxe guztiek parte hartuko dute.' },
  { id: '35', mota: 'Jarraipena', antolatzaileak: 'Gisa berean...', esanahia: 'De la misma manera...', adibidez: 'Gisa berean, familia guztiak informatuko dira.' },
  { id: '36', mota: 'Jarraipena', antolatzaileak: 'Modu berean...', esanahia: 'De la misma forma...', adibidez: 'Modu berean, beste udalerri batzuetan ere egingo da.' },
  { id: '37', mota: 'Amaiera', antolatzaileak: 'Amaitzeko...', esanahia: 'Para terminar...', adibidez: 'Amaitzeko, galdera batzuk erantzungo ditugu.' },
  { id: '38', mota: 'Amaiera', antolatzaileak: 'Bukatzeko...', esanahia: 'Para concluir...', adibidez: 'Bukatzeko, ondorio nagusiak aurkeztuko ditut.' },
  { id: '39', mota: 'Amaiera', antolatzaileak: 'Amaitzeko (bukatzeko), esan behar da...', esanahia: 'Para acabar, hay que decir que...', adibidez: 'Amaitzeko, esan behar da emaitza onak lortu direla.' },
  { id: '40', mota: 'Amaiera', antolatzaileak: 'Azkenik (azkenez)...', esanahia: 'Finalmente...', adibidez: 'Azkenik, eskerrak eman nahi dizkiet guztiei.' },
  { id: '41', mota: 'Amaiera', antolatzaileak: 'Laburbilduz...', esanahia: 'En resumen...', adibidez: 'Laburbilduz, ideia nagusi hauek dira.' },
  { id: '42', mota: 'Amaiera', antolatzaileak: 'Esandakoa laburtzeko...', esanahia: 'Para resumir lo dicho...', adibidez: 'Esandakoa laburtzeko, hiru puntu nabarmendu ditugu.' },
  { id: '43', mota: 'Amaiera', antolatzaileak: 'Laburpen gisa...', esanahia: 'A modo de resumen...', adibidez: 'Laburpen gisa, hauxe da esan nahi izan duguna.' },
  { id: '44', mota: 'Amaiera', antolatzaileak: 'Hitz gutxitan: ...', esanahia: 'En pocas palabras...', adibidez: 'Hitz gutxitan: emaitza bikaina da.' },
  { id: '45', mota: 'Amaiera', antolatzaileak: 'Ondorio gisa...', esanahia: 'A modo de conclusión...', adibidez: 'Ondorio gisa, neurri berriak hartu behar dira.' },
  { id: '46', mota: 'Amaiera', antolatzaileak: 'Honenbestez...', esanahia: 'Por tanto...', adibidez: 'Honenbestez, proiektua amaitutzat ematen da.' },
  { id: '47', mota: 'Amaiera', antolatzaileak: 'Eta besterik gabe...', esanahia: 'Y sin más...', adibidez: 'Eta besterik gabe, agur esan behar dizuet.' },
  { id: '48', mota: 'Amaiera', antolatzaileak: 'Eta agurtzeko...', esanahia: 'Y para despedir...', adibidez: 'Eta agurtzeko, eskerrik asko parte hartzeagatik.' },
  { id: '49', mota: 'Amaiera', antolatzaileak: 'Eta (hitzaldiari) amaiera emateko...', esanahia: 'Y para poner fin (a la charla)...', adibidez: 'Eta hitzaldiari amaiera emateko, galderak jasoko ditugu.' },
  { id: '50', mota: 'Ordena', antolatzaileak: 'Lehenik... bigarrenik... hirugarrenik...', esanahia: 'Primero... segundo... tercero...', adibidez: 'Lehenik, gai nagusia azalduko dugu; bigarrenik, adibideak emango ditugu.' },
  { id: '51', mota: 'Ordena', antolatzaileak: 'Arestian esan bezala...', esanahia: 'Como se dijo anteriormente...', adibidez: 'Arestian esan bezala, hau ez da lehen aldia.' },
  { id: '52', mota: 'Ordena', antolatzaileak: 'Gorago aipatu bezala...', esanahia: 'Como se mencionó más arriba...', adibidez: 'Gorago aipatu bezala, bi aukera daude.' },
  { id: '53', mota: 'Ordena', antolatzaileak: 'Lehen(ago) esan bezala...', esanahia: 'Como se dijo antes...', adibidez: 'Lehenago esan bezala, emaitzak ez dira egokiak izan.' },
  { id: '54', mota: 'Ordena', antolatzaileak: 'Geroago ikusiko dugun bezala...', esanahia: 'Como veremos más adelante...', adibidez: 'Geroago ikusiko dugun bezala, beste faktore batzuk ere badaude.' },
  { id: '55', mota: 'Ordena', antolatzaileak: 'Aurrerago ikusiko dugunez...', esanahia: 'Como veremos más adelante...', adibidez: 'Aurrerago ikusiko dugunez, prozesua konplexua da.' },
  { id: '56', mota: 'Ordena', antolatzaileak: 'Alde batetik... beste alde batetik...', esanahia: 'Por un lado... por otro lado...', adibidez: 'Alde batetik, aurrekontua txikia da; beste alde batetik, epeak laburrak dira.' },
  { id: '57', mota: 'Ordena', antolatzaileak: 'Batzuetan... beste batzuetan...', esanahia: 'A veces... otras veces...', adibidez: 'Batzuetan arrakasta izaten dute; beste batzuetan, ez horrenbeste.' },
  { id: '58', mota: 'Ordena', antolatzaileak: 'Hasteko... jarraitzeko...', esanahia: 'Para comenzar... para continuar...', adibidez: 'Hasteko azalpen teorikoa emango dugu, jarraitzeko ariketa praktikoak.' },
  { id: '59', mota: 'Ordena', antolatzaileak: 'Batetikik... bestetik...', esanahia: 'Por una parte... por otra parte...', adibidez: 'Batetikik, egoera ekonomikoa aztertuko dugu; bestetik, soziala.' },
  { id: '60', mota: 'Ordena', antolatzaileak: 'Bateko... besteko...', esanahia: 'De una... de otra...', adibidez: 'Bateko informazioa jasoko dugu; besteko proposamenak aztertuko ditugu.' },
  { id: '61', mota: 'Lehentasuna', antolatzaileak: 'Batez ere...', esanahia: 'Sobre todo...', adibidez: 'Batez ere, segurtasuna bermatu behar dugu.' },
  { id: '62', mota: 'Lehentasuna', antolatzaileak: 'Batik bat...', esanahia: 'Principalmente...', adibidez: 'Batik bat, gazteentzako jarduerak antolatuko dira.' },
  { id: '63', mota: 'Lehentasuna', antolatzaileak: 'Nagusiki...', esanahia: 'Fundamentalmente...', adibidez: 'Nagusiki, bi gai nagusi landuko ditugu.' },
  { id: '64', mota: 'Lehentasuna', antolatzaileak: 'Eta bereziki...', esanahia: 'Y especialmente...', adibidez: 'Eta bereziki, ingurumenaren zaintza azpimarratu nahi dugu.' },
  { id: '65', mota: 'Lehentasuna', antolatzaileak: 'Gauza guztien gainetik...', esanahia: 'Por encima de todo...', adibidez: 'Gauza guztien gainetik, osasuna dago.' },
  { id: '66', mota: 'Lehentasuna', antolatzaileak: 'Horren gainetik...', esanahia: 'Por encima de eso...', adibidez: 'Horren gainetik, hezkuntza lehenetsi behar da.' },
  { id: '67', mota: 'Lehentasuna', antolatzaileak: 'Beste maila batean...', esanahia: 'En otro nivel...', adibidez: 'Beste maila batean, kultur eskaintza dago.' },
  { id: '68', mota: 'Lehentasuna', antolatzaileak: 'Ezer baino lehen...', esanahia: 'Antes que nada...', adibidez: 'Ezer baino lehen, arauak gogoratu behar ditugu.' },
  { id: '69', mota: 'Lehentasuna', antolatzaileak: '... ez bezala', esanahia: 'A diferencia de...', adibidez: 'Hau ez da aurreko ekitaldia bezalakoa izan.' },
  { id: '70', mota: 'Lehentasuna', antolatzaileak: 'Denetan garrantzitsuena...', esanahia: 'Lo más importante de todo...', adibidez: 'Denetan garrantzitsuena, elkarbizitza da.' },
  { id: '71', mota: 'Lehentasuna', antolatzaileak: 'Baten bat aipatzekotan...', esanahia: 'Si hay que destacar uno...', adibidez: 'Baten bat aipatzekotan, lehenengo proposamena nabarmenduko nuke.' },
  { id: '72', mota: 'Indartzea', antolatzaileak: 'Batez ere...', esanahia: 'Sobre todo...', adibidez: 'Batez ere, segurtasuna bermatu behar dugu.' },
  { id: '73', mota: 'Indartzea', antolatzaileak: 'Batik bat...', esanahia: 'Principalmente...', adibidez: 'Batik bat, irakasleen lana azpimarratu behar da.' },
  { id: '74', mota: 'Indartzea', antolatzaileak: 'Nagusiki...', esanahia: 'Fundamentalmente...', adibidez: 'Nagusiki, bi gai jorratuko ditugu.' },
  { id: '75', mota: 'Indartzea', antolatzaileak: 'Bereziki...', esanahia: 'Especialmente...', adibidez: 'Bereziki, haurrei zuzenduta dago.' },
  { id: '76', mota: 'Indartzea', antolatzaileak: 'Gainera...', esanahia: 'Además...', adibidez: 'Gainera, epeak betetzen dira.' },
  { id: '77', mota: 'Indartzea', antolatzaileak: 'Horrez gain...', esanahia: 'Además de eso...', adibidez: 'Horrez gain, laguntza ekonomikoa jasoko dute.' },
  { id: '78', mota: 'Indartzea', antolatzaileak: 'Horretaz gainera...', esanahia: 'Aparte de eso...', adibidez: 'Horretaz gainera, aukera berriak sortuko dira.' },
  { id: '79', mota: 'Indartzea', antolatzaileak: 'Hain zuzen ere...', esanahia: 'Precisamente...', adibidez: 'Hain zuzen ere, horregatik hartu da erabaki hori.' },
  { id: '80', mota: 'Indartzea', antolatzaileak: 'Gutxienez...', esanahia: 'Al menos...', adibidez: 'Gutxienez, bi aukera aztertu behar dira.' },
  { id: '81', mota: 'Indartzea', antolatzaileak: 'Bestela esanda...', esanahia: 'Dicho de otro modo...', adibidez: 'Bestela esanda, ez dago beste aukerarik.' },
  { id: '82', mota: 'Indartzea', antolatzaileak: 'Beste era batera esanda...', esanahia: 'En otras palabras...', adibidez: 'Beste era batera esanda, berak du ardura osoa.' },
  { id: '83', mota: 'Indartzea', antolatzaileak: 'Daki(ke)zuenez...', esanahia: 'Como sabéis...', adibidez: 'Dakizuen bezala, egoera ez da erraza.' },
  { id: '84', mota: 'Indartzea', antolatzaileak: 'Jakingo duzuenez...', esanahia: 'Como sabréis...', adibidez: 'Jakingo duzuenez, aldaketak egin dira.' },
  { id: '85', mota: 'Indartzea', antolatzaileak: 'Hobeto esanda...', esanahia: 'Mejor dicho...', adibidez: 'Hobeto esanda, ez da nahikoa izan.' },
  { id: '86', mota: 'Indartzea', antolatzaileak: 'Zehatzago esanda...', esanahia: 'Dicho con más precisión...', adibidez: 'Zehatzago esanda, 20 ikasle izango dira.' },
  { id: '87', mota: 'Indartzea', antolatzaileak: 'Berriro esanda...', esanahia: 'Repitiendo...', adibidez: 'Berriro esanda, ez da onargarria.' },
  { id: '88', mota: 'Indartzea', antolatzaileak: 'Berriro esango dut...', esanahia: 'Lo repetiré...', adibidez: 'Berriro esango dut, ezin dugu onartu.' },
  { id: '89', mota: 'Indartzea', antolatzaileak: 'Berez...', esanahia: 'En sí...', adibidez: 'Berez, ideia ez da txarra.' },
  { id: '90', mota: 'Indartzea', antolatzaileak: 'Benetan (ere)...', esanahia: 'Realmente...', adibidez: 'Benetan, harrituta geratu ginen.' },
  { id: '91', mota: 'Indartzea', antolatzaileak: 'Zinez...', esanahia: 'De verdad...', adibidez: 'Zinez, lan handia egin dute.' },
  { id: '92', mota: 'Indartzea', antolatzaileak: 'Hori azpimarratzeko...', esanahia: 'Para destacar eso...', adibidez: 'Hori azpimarratzeko, datuak erakutsiko ditugu.' },
  { id: '93', mota: 'Indartzea', antolatzaileak: 'Azpimarratzekoa da...', esanahia: 'Cabe destacar que...', adibidez: 'Azpimarratzekoa da ikasleen parte-hartzea.' },
  { id: '94', mota: 'Indartzea', antolatzaileak: 'Aipamen berezia merezi du...', esanahia: 'Merece una mención especial...', adibidez: 'Aipamen berezia merezi du zuzendariak.' },
  { id: '95', mota: 'Indartzea', antolatzaileak: 'Hori ez ezik... ere', esanahia: 'No solo eso, sino también...', adibidez: 'Hori ez ezik, beste neurri batzuk ere hartu dira.' },
  { id: '96', mota: 'Indartzea', antolatzaileak: 'Eta ez hori bakarrik...', esanahia: 'Y no solo eso...', adibidez: 'Eta ez hori bakarrik, baizik eta gehiago ere bai.' },
  { id: '97', mota: 'Indartzea', antolatzaileak: 'Hori gutxi balitz bezala...', esanahia: 'Como si fuera poco...', adibidez: 'Hori gutxi balitz bezala, isunak jarri dizkiete.' },
  { id: '98', mota: 'Orobatasuna', antolatzaileak: 'Era berean...', esanahia: 'Del mismo modo...', adibidez: 'Era berean, beste irtenbide bat proposatu zen.' },
  { id: '99', mota: 'Orobatasuna', antolatzaileak: 'Gisa berean...', esanahia: 'De la misma manera...', adibidez: 'Gisa berean, ekintza gehiago egin dira.' },
  { id: '100', mota: 'Orobatasuna', antolatzaileak: 'Modu berean...', esanahia: 'Igualmente...', adibidez: 'Modu berean, beste ikerketa bat burutu da.' },
  { id: '101', mota: 'Orobatasuna', antolatzaileak: 'Halaber...', esanahia: 'Asimismo...', adibidez: 'Halaber, txostena sinatu zuten.' },
  { id: '102', mota: 'Orobatasuna', antolatzaileak: 'Orobat...', esanahia: 'También...', adibidez: 'Orobat, bestelako arauak ezarri dira.' },
  { id: '103', mota: 'Orobatasuna', antolatzaileak: 'Berebat...', esanahia: 'Igualmente...', adibidez: 'Berebat, partaideek adostasuna lortu zuten.' },
  { id: '104', mota: 'Orobatasuna', antolatzaileak: 'Bezala / legez / moduan', esanahia: 'Como / según / del modo en que', adibidez: 'Ikasleek irakasleek bezala jardun zuten.' },
  { id: '105', mota: 'Orobatasuna', antolatzaileak: 'Beza(i)n (konparazioa)', esanahia: 'Tan... como (comparativo)', adibidez: 'Hau bezain ona da beste hori ere.' },
  { id: '106', mota: 'Orobatasuna', antolatzaileak: 'Beste, adina (konparazioa)', esanahia: 'Tanto... como...', adibidez: 'Honek beste adina balio du.' },
  { id: '107', mota: 'Orobatasuna', antolatzaileak: 'Bai... bai...', esanahia: 'Tanto... como...', adibidez: 'Bai irakasleak, bai ikasleak pozik daude.' },
  { id: '108', mota: 'Orobatasuna', antolatzaileak: 'Ez... ez...', esanahia: 'Ni... ni...', adibidez: 'Ez ikasleak, ez irakasleak etorri dira.' },
  { id: '109', mota: 'Orobatasuna', antolatzaileak: 'Dela... dela...', esanahia: 'Sea... sea...', adibidez: 'Dela eguraldiagatik, dela trafikoagatik, berandu iritsi da.' },
  { id: '110', mota: 'Orobatasuna', antolatzaileak: 'Oro har...', esanahia: 'En general...', adibidez: 'Oro har, emaitzak onak izan dira.' },
  { id: '111', mota: 'Orobatasuna', antolatzaileak: 'Batez beste...', esanahia: 'Como media...', adibidez: 'Batez beste, 10 puntu lortu dituzte.' },
  { id: '112', mota: 'Orobatasuna', antolatzaileak: 'Beste batzuen artean...', esanahia: 'Entre otros...', adibidez: 'Beste batzuen artean, bera ere izan zen hautagaia.' },
  { id: '113', mota: 'Orobatasuna', antolatzaileak: 'Horren antzera...', esanahia: 'De forma parecida...', adibidez: 'Horren antzera, beste herrietan ere egin dute.' },
  { id: '114', mota: 'Orobatasuna', antolatzaileak: 'Neurri berean...', esanahia: 'En la misma medida...', adibidez: 'Neurri berean zigortuak izan dira.' },
  { id: '115', mota: 'Orobatasuna', antolatzaileak: 'Hein berean...', esanahia: 'En el mismo grado...', adibidez: 'Hein berean, arduratsua da.' },
  { id: '116', mota: 'Orobatasuna', antolatzaileak: 'Maila berean...', esanahia: 'En el mismo nivel...', adibidez: 'Maila berean daude bi hautagaiak.' },
  { id: '117', mota: 'Orobatasuna', antolatzaileak: 'Zentzu berean...', esanahia: 'En el mismo sentido...', adibidez: 'Zentzuz berean jokatzen dute.' },
  { id: '118', mota: 'Orobatasuna', antolatzaileak: 'Ildo (hari) beretik...', esanahia: 'En la misma línea...', adibidez: 'Ildo beretik, erabaki bera hartu dute.' },
  { id: '119', mota: 'Kontrastea', antolatzaileak: 'Hala ere', esanahia: 'Sin embargo', adibidez: 'Hala ere, saiatuko gara berriro.' },
  { id: '120', mota: 'Kontrastea', antolatzaileak: 'Hala eta guztiz ere...', esanahia: 'Aun así...', adibidez: 'Hala eta guztiz ere, ez du onartu.' },
  { id: '121', mota: 'Kontrastea', antolatzaileak: 'Aitzitik...', esanahia: 'Al contrario...', adibidez: 'Aitzitik, aurka bozkatu zuen.' },
  { id: '122', mota: 'Kontrastea', antolatzaileak: 'Nolanahi ere (den)...', esanahia: 'Sea como sea...', adibidez: 'Nolanahi ere, emaitza bera da.' },
  { id: '123', mota: 'Kontrastea', antolatzaileak: 'Edonola (edozein modutan) ere...', esanahia: 'De todos modos...', adibidez: 'Edonola ere, irtenbidea aurkitu behar dugu.' },
  { id: '124', mota: 'Kontrastea', antolatzaileak: 'Zernahi gisaz ere...', esanahia: 'Sea cual sea la forma...', adibidez: 'Zernahi gisaz ere, ez gara amore emango.' },
  { id: '125', mota: 'Kontrastea', antolatzaileak: 'Dena dela (dena den)...', esanahia: 'De todas formas...', adibidez: 'Dena dela, parte hartzea eskertzen dugu.' },
  { id: '126', mota: 'Kontrastea', antolatzaileak: 'Datorrena datorrela...', esanahia: 'Pase lo que pase...', adibidez: 'Datorrena datorrela, prest egon behar dugu.' },
  { id: '127', mota: 'Kontrastea', antolatzaileak: 'Esaten duena esaten duela...', esanahia: 'Diga lo que diga...', adibidez: 'Esaten duena esaten duela, guk gurea egingo dugu.' },
  { id: '128', mota: 'Kontrastea', antolatzaileak: 'Esandakoaren aurka...', esanahia: 'En contra de lo dicho...', adibidez: 'Esandakoaren aurka doa erabaki hau.' },
  { id: '129', mota: 'Kontrastea', antolatzaileak: 'Uste genuenaren kontra...', esanahia: 'Contrario a lo que creíamos...', adibidez: 'Uste genuenaren kontra gertatu zen dena.' },
  { id: '130', mota: 'Kontrastea', antolatzaileak: 'Uste ez bezala...', esanahia: 'Contrariamente a lo esperado...', adibidez: 'Uste ez bezala, emaitza onak lortu dituzte.' },
  { id: '131', mota: 'Kontrastea', antolatzaileak: 'Esanak esan...', esanahia: 'Digan lo que digan...', adibidez: 'Esanak esan, ez dute ezer aldatu.' },
  { id: '132', mota: 'Kontrastea', antolatzaileak: 'Eginak egin...', esanahia: 'Hagan lo que hagan...', adibidez: 'Eginak egin, ez zuten konpondu arazoa.' },
  { id: '133', mota: 'Kontrastea', antolatzaileak: 'Usteak uste...', esanahia: 'Crean lo que crean...', adibidez: 'Usteak uste, datuek beste zerbait diote.' },
  { id: '134', mota: 'Kontrastea', antolatzaileak: 'Iritziak iritzi...', esanahia: 'Opinen lo que opinen...', adibidez: 'Iritziak iritzi, erabakia hartu dute.' },
  { id: '135', mota: 'Kontrastea', antolatzaileak: 'Horregatik ere...', esanahia: 'Aun así...', adibidez: 'Horregatik ere, ez zen justua izan.' },
  { id: '136', mota: 'Kontrastea', antolatzaileak: 'Hori gorabehera...', esanahia: 'A pesar de eso...', adibidez: 'Hori gorabehera, aurrera jarraituko dugu.' },
  { id: '137', mota: 'Denbora', antolatzaileak: 'Lehen(ago)...', esanahia: 'Antes...', adibidez: 'Lehenago iritsi zen gu baino.' },
  { id: '138', mota: 'Denbora', antolatzaileak: 'Horren aurretik...', esanahia: 'Antes de eso...', adibidez: 'Horren aurretik, bilera bat izan genuen.' },
  { id: '139', mota: 'Denbora', antolatzaileak: 'Arestian...', esanahia: 'Hace un momento...', adibidez: 'Arestian aipatu dudan moduan, garrantzitsua da.' },
  { id: '140', mota: 'Denbora', antolatzaileak: 'Oraindik orain...', esanahia: 'Hasta hace poco...', adibidez: 'Oraindik orain iritsi da berria.' },
  { id: '141', mota: 'Denbora', antolatzaileak: 'Duela gutxi...', esanahia: 'Hace poco...', adibidez: 'Duela gutxi ikusi dut.' },
  { id: '142', mota: 'Denbora', antolatzaileak: 'Orain...', esanahia: 'Ahora...', adibidez: 'Orain ez da momentu egokia.' },
  { id: '143', mota: 'Denbora', antolatzaileak: 'Oraintxe bertan...', esanahia: 'Justo ahora...', adibidez: 'Oraintxe bertan hasiko gara.' },
  { id: '144', mota: 'Denbora', antolatzaileak: 'Orain arte...', esanahia: 'Hasta ahora...', adibidez: 'Orain arte ez dugu ezer jakin.' },
  { id: '145', mota: 'Denbora', antolatzaileak: 'Une honetan...', esanahia: 'En este momento...', adibidez: 'Une honetan ez dago erabilgarri.' },
  { id: '146', mota: 'Denbora', antolatzaileak: 'Gero (ago)...', esanahia: 'Después (más tarde)...', adibidez: 'Gero joango gara erosketak egitera.' },
  { id: '147', mota: 'Denbora', antolatzaileak: 'Ondoren...', esanahia: 'Después...', adibidez: 'Ondoren, bazkaria egingo dugu.' },
  { id: '148', mota: 'Denbora', antolatzaileak: 'Hemendik aurrera...', esanahia: 'A partir de ahora...', adibidez: 'Hemendik aurrera zuzendari berria izango da.' },
  { id: '149', mota: 'Denbora', antolatzaileak: 'Horren ondoren...', esanahia: 'Después de eso...', adibidez: 'Horren ondoren, txalo zaparrada izan zen.' },
  { id: '150', mota: 'Denbora', antolatzaileak: 'Horren ostean...', esanahia: 'Tras eso...', adibidez: 'Horren ostean, prentsaurrekoa eman zuen.' },
  { id: '151', mota: 'Denbora', antolatzaileak: 'Dagoeneko...', esanahia: 'Ya...', adibidez: 'Dagoeneko amaitu da ikasturtea.' },
  { id: '152', mota: 'Denbora', antolatzaileak: 'Honezkero...', esanahia: 'Ya para entonces...', adibidez: 'Honezkero egina behar zuen.' },
  { id: '153', mota: 'Denbora', antolatzaileak: 'Horrezkero...', esanahia: 'Desde entonces...', adibidez: 'Horrezkero aldaketa asko gertatu dira.' },
  { id: '154', mota: 'Denbora', antolatzaileak: 'Harrezkero...', esanahia: 'Desde entonces...', adibidez: 'Harrezkero ez dut gehiago ikusi.' },
  { id: '155', mota: 'Denbora', antolatzaileak: 'Orduan...', esanahia: 'En aquel momento...', adibidez: 'Orduan konturatu ginen arazoaz.' },
  { id: '156', mota: 'Denbora', antolatzaileak: 'Ordura arte...', esanahia: 'Hasta aquel momento...', adibidez: 'Ordura arte ez zen ezer gertatu.' },
  { id: '157', mota: 'Denbora', antolatzaileak: 'Une horretan (hartan)...', esanahia: 'En aquel instante...', adibidez: 'Une horretan erabaki zuten aldaketa egitea.' },
  { id: '158', mota: 'Denbora', antolatzaileak: 'Garai (sasoi) hartan...', esanahia: 'En aquella época...', adibidez: 'Garai hartan ez zegoen hainbeste teknologia.' },
  { id: '159', mota: 'Denbora', antolatzaileak: 'Garai (sasoi) batean...', esanahia: 'En una época...', adibidez: 'Garai batean, ohikoa zen hori egitea.' },
  { id: '160', mota: 'Denbora', antolatzaileak: 'Hasieran...', esanahia: 'Al principio...', adibidez: 'Hasieran dena zaila zen.' },
  { id: '161', mota: 'Denbora', antolatzaileak: 'Hasiera batean...', esanahia: 'Al inicio...', adibidez: 'Hasiera batean ez nuen ezer ulertu.' },
  { id: '162', mota: 'Denbora', antolatzaileak: 'Amaieran...', esanahia: 'Al final...', adibidez: 'Amaieran, dena ondo atera zen.' },
  { id: '163', mota: 'Denbora', antolatzaileak: 'Azkenean...', esanahia: 'Finalmente...', adibidez: 'Azkenean lortu genuen helburua.' },
  { id: '164', mota: 'Denbora', antolatzaileak: 'Egun batean...', esanahia: 'Un día...', adibidez: 'Egun batean, erabaki zuen joatea.' },
  { id: '165', mota: 'Denbora', antolatzaileak: 'Egun hartan...', esanahia: 'Aquel día...', adibidez: 'Egun hartan ez zen inor etorri.' },
  { id: '166', mota: 'Denbora', antolatzaileak: 'Aspaldi (an)...', esanahia: 'Hace mucho tiempo...', adibidez: 'Aspaldian ez dut horrelakorik ikusi.' },
  { id: '167', mota: 'Denbora', antolatzaileak: 'Antzina...', esanahia: 'Antiguamente...', adibidez: 'Antzina ohitura hori oso zabalduta zegoen.' },
  { id: '168', mota: 'Denbora', antolatzaileak: 'Behiala...', esanahia: 'En tiempos pasados...', adibidez: 'Behiala baserriak asko ziren.' },
  { id: '169', mota: 'Denbora', antolatzaileak: 'Halako batean...', esanahia: 'De pronto...', adibidez: 'Halako batean, zarata entzun zen.' },
  { id: '170', mota: 'Denbora', antolatzaileak: 'Bat-batean...', esanahia: 'De repente...', adibidez: 'Bat-batean euria hasi zuen.' },
  { id: '171', mota: 'Denbora', antolatzaileak: 'Behin (batean)...', esanahia: 'Una vez...', adibidez: 'Behin batean, ume bat galdu zen basoan.' },
  { id: '172', mota: 'Denbora', antolatzaileak: 'Bazen behin...', esanahia: 'Érase una vez...', adibidez: 'Bazen behin errege bat...' },
  { id: '173', mota: 'Lekua', antolatzaileak: 'Hemen, hor, han...', esanahia: 'Aquí, ahí, allí...', adibidez: 'Hemen utzi dugu aurrekoa, han jarraituko dugu.' },
  { id: '174', mota: 'Lekua', antolatzaileak: 'Goian / behean...', esanahia: 'Arriba / abajo...', adibidez: 'Goian dagoen irudian ikus daiteke.' },
  { id: '175', mota: 'Lekua', antolatzaileak: 'Gorago / beherago...', esanahia: 'Más arriba / más abajo...', adibidez: 'Gorago aipatu dugun bezala, garrantzitsua da.' },
  { id: '176', mota: 'Lekua', antolatzaileak: 'Aurrean / atzean...', esanahia: 'Delante / detrás...', adibidez: 'Aurrean eserita daude ikasleak, atzean gurasoak.' },
  { id: '177', mota: 'Lekua', antolatzaileak: 'Ezkerrean / eskuinetara...', esanahia: 'A la izquierda / a la derecha...', adibidez: 'Ezkererra joan behar da sarreratik.' },
  { id: '178', mota: 'Lekua', antolatzaileak: 'Ezkerraldera / eskuinaldera...', esanahia: 'En el lado izquierdo / derecho...', adibidez: 'Ezkerraldera kokatu zuten mahaia.' },
  { id: '179', mota: 'Lekua', antolatzaileak: 'Aurreko / hurrengo atalean...', esanahia: 'En el apartado anterior / siguiente...', adibidez: 'Aurreko atalean azaldu genuen kontzeptua.' },
  { id: '180', mota: 'Lekua', antolatzaileak: 'Gorago ikusi dugunez...', esanahia: 'Como vimos más arriba...', adibidez: 'Gorago ikusi dugunez, emaitza positiboa da.' },
  { id: '181', mota: 'Lekua', antolatzaileak: 'Aurreko atalean esan dugunez...', esanahia: 'Como dijimos en el apartado anterior...', adibidez: 'Aurreko atalean esan dugunez, metodologia hau eraginkorra da.' },
  { id: '182', mota: 'Lekua', antolatzaileak: 'Horren aurretik / atzetik...', esanahia: 'Antes / después de eso...', adibidez: 'Horren aurretik beste ikerketa bat egin zen.' },
  { id: '183', mota: 'Lekua', antolatzaileak: 'Beste maila batean...', esanahia: 'En otro nivel...', adibidez: 'Beste maila batean dagoen ikuspegia da.' },
  { id: '184', mota: 'Anaforikoak', antolatzaileak: 'Esan bezala...', esanahia: 'Como se ha dicho...', adibidez: 'Esan bezala, ez da erraza izango.' },
  { id: '185', mota: 'Anaforikoak', antolatzaileak: 'Gorago aipatu bezala...', esanahia: 'Como se mencionó más arriba...', adibidez: 'Gorago aipatu bezala, datuak argigarriak dira.' },
  { id: '186', mota: 'Anaforikoak', antolatzaileak: 'Esan dugun bezala...', esanahia: 'Como hemos dicho...', adibidez: 'Esan dugun bezala, kontuz ibili behar da.' },
  { id: '187', mota: 'Anaforikoak', antolatzaileak: 'Esan berri dugunez...', esanahia: 'Como acabamos de decir...', adibidez: 'Esan berri dugunez, orain beste fase bat hasiko da.' },
  { id: '188', mota: 'Anaforikoak', antolatzaileak: 'Gorago aipatu dugunez...', esanahia: 'Como hemos mencionado más arriba...', adibidez: 'Gorago aipatu dugunez, hori ezin da ahaztu.' },
  { id: '189', mota: 'Anaforikoak', antolatzaileak: 'Arestian aipatu dugunez...', esanahia: 'Como hemos mencionado antes...', adibidez: 'Arestian aipatu dugunez, garrantzitsua da kontuan hartzea.' },
  { id: '190', mota: 'Anaforikoak', antolatzaileak: 'Arestian esan bezala...', esanahia: 'Como se dijo anteriormente...', adibidez: 'Arestian esan bezala, ohiko prozedura jarraituko dugu.' },
  { id: '191', mota: 'Anaforikoak', antolatzaileak: 'Testuan zehar azaldu denez...', esanahia: 'Como se ha explicado a lo largo del texto...', adibidez: 'Testuan zehar azaldu denez, prozesua konplexua da.' },
  { id: '192', mota: 'Anaforikoak', antolatzaileak: 'Aurreko atalean ikusi dugunez...', esanahia: 'Como vimos en el apartado anterior...', adibidez: 'Aurreko atalean ikusi dugunez, emaitzak onak izan dira.' },
  { id: '193', mota: 'Anaforikoak', antolatzaileak: 'Aurreko adibidean ikus daitekeenez...', esanahia: 'Como puede verse en el ejemplo anterior...', adibidez: 'Aurreko adibidean ikus daitekeenez, ez da beti berdina gertatzen.' },
  { id: '194', mota: 'Kataforikoak', antolatzaileak: 'Honako hauek...', esanahia: 'Los siguientes...', adibidez: 'Honako hauek dira arauak: ...' },
  { id: '195', mota: 'Kataforikoak', antolatzaileak: 'Hona hemen...', esanahia: 'He aquí...', adibidez: 'Hona hemen azalpen labur bat.' },
  { id: '196', mota: 'Kataforikoak', antolatzaileak: 'Hurrengo atalean ikusiko dugunez...', esanahia: 'Como veremos en el siguiente apartado...', adibidez: 'Hurrengo atalean ikusiko dugunez, emaitzek gora egin dute.' },
  { id: '197', mota: 'Kataforikoak', antolatzaileak: 'Berehala ikusiko dugunez...', esanahia: 'Como veremos en breve...', adibidez: 'Berehala ikusiko dugunez, badira salbuespenak ere.' },
  { id: '198', mota: 'Kataforikoak', antolatzaileak: 'Beherago azalduko dugunez...', esanahia: 'Como explicaremos más abajo...', adibidez: 'Beherago azalduko dugunez, ez da beti horrela.' },
  { id: '199', mota: 'Kataforikoak', antolatzaileak: 'Hurrengo taulan ikus daitekeenez...', esanahia: 'Como puede verse en la siguiente tabla...', adibidez: 'Hurrengo taulan ikus daitekeenez, kopurua handitu da.' },
  { id: '200', mota: 'Ustea edo iritzia', antolatzaileak: 'Nire iritziz...', esanahia: 'En mi opinión...', adibidez: 'Nire iritziz, hori ez da zuzena.' },
  { id: '201', mota: 'Ustea edo iritzia', antolatzaileak: 'Gure iritzian...', esanahia: 'En nuestra opinión...', adibidez: 'Gure iritzian, beste bide bat hartu beharko litzateke.' },
  { id: '202', mota: 'Ustea edo iritzia', antolatzaileak: 'Nire ustez...', esanahia: 'A mi parecer...', adibidez: 'Nire ustez, hori ez da bidezkoa.' },
  { id: '203', mota: 'Ustea edo iritzia', antolatzaileak: 'Nire iritzia esango dizut...', esanahia: 'Te diré mi opinión...', adibidez: 'Nire iritzia esango dizut: ez da erraza.' },
  { id: '204', mota: 'Ustea edo iritzia', antolatzaileak: 'Iritziak iritzi...', esanahia: 'Opiniones hay muchas...', adibidez: 'Iritziak iritzi, erabakia hartua dago.' },
  { id: '205', mota: 'Ustea edo iritzia', antolatzaileak: 'Nik uste...', esanahia: 'Yo creo...', adibidez: 'Nik uste ez dela egokia.' },
  { id: '206', mota: 'Ustea edo iritzia', antolatzaileak: 'Guk uste...', esanahia: 'Nosotros creemos...', adibidez: 'Guk uste hau dela aukerarik onena.' },
  { id: '207', mota: 'Ustea edo iritzia', antolatzaileak: 'Batzuen iritziz...', esanahia: 'Según algunos...', adibidez: 'Batzuen iritziz, hori alferrikakoa da.' },
  { id: '208', mota: 'Ustea edo iritzia', antolatzaileak: 'Gehiengoaren iritziz...', esanahia: 'Según la mayoría...', adibidez: 'Gehiengoaren iritziz, neurri egokia izan da.' },
  { id: '209', mota: 'Ustea edo iritzia', antolatzaileak: 'Jendearen ustez...', esanahia: 'Según la gente...', adibidez: 'Jendearen ustez, arazoa konponduta dago.' },
  { id: '210', mota: 'Ustea edo iritzia', antolatzaileak: 'Nire aburuz...', esanahia: 'Según mi criterio...', adibidez: 'Nire aburuz, proposamena egokia da.' },
  { id: '211', mota: 'Ustea edo iritzia', antolatzaileak: 'Ene irudiko...', esanahia: 'En mi parecer...', adibidez: 'Ene irudiko, neurriz kanpokoa da erreakzioa.' },
  { id: '212', mota: 'Ustea edo iritzia', antolatzaileak: 'Nire uste apalean...', esanahia: 'A mi humilde parecer...', adibidez: 'Nire uste apalean, ez da aukera egokia.' },
  { id: '213', mota: 'Ustea edo iritzia', antolatzaileak: 'Uste bezala...', esanahia: 'Como se cree...', adibidez: 'Uste bezala, emaitza positiboa izan da.' },
  { id: '214', mota: 'Ustea edo iritzia', antolatzaileak: 'Uste ez bezala...', esanahia: 'Contrariamente a lo que se cree...', adibidez: 'Uste ez bezala, ez da onartu.' },
  { id: '215', mota: 'Ziurtasuna', antolatzaileak: 'Zalantzarik gabe...', esanahia: 'Sin lugar a dudas...', adibidez: 'Zalantzarik gabe, hori da aukera onena.' },
  { id: '216', mota: 'Ziurtasuna', antolatzaileak: 'Duda barik...', esanahia: 'Sin duda...', adibidez: 'Duda barik, lehenengo izango da.' },
  { id: '217', mota: 'Ziurtasuna', antolatzaileak: 'Ez dago zalantzarik...', esanahia: 'No hay duda de que...', adibidez: 'Ez dago zalantzarik arrakastatsua izango dela.' },
  { id: '218', mota: 'Ziurtasuna', antolatzaileak: 'Gauza jakina da...', esanahia: 'Es un hecho sabido...', adibidez: 'Gauza jakina da hori gertatuko dela.' },
  { id: '219', mota: 'Ziurtasuna', antolatzaileak: 'Jakina...', esanahia: 'Por supuesto...', adibidez: 'Jakina, prest gaude laguntzeko.' },
  { id: '220', mota: 'Ziurtasuna', antolatzaileak: 'Noski...', esanahia: 'Claro...', adibidez: 'Noski, zurekin ados nago.' },
  { id: '221', mota: 'Ziurtasuna', antolatzaileak: 'Egia da...', esanahia: 'Es verdad...', adibidez: 'Egia da hori ez dela erraza.' },
  { id: '222', mota: 'Ziurtasuna', antolatzaileak: 'Bistan da...', esanahia: 'Es evidente...', adibidez: 'Bistan da ez dela nahikoa.' },
  { id: '223', mota: 'Ziurtasuna', antolatzaileak: 'Argi dago...', esanahia: 'Está claro...', adibidez: 'Argi dago arazo bat dagoela.' },
  { id: '224', mota: 'Ziurtasuna', antolatzaileak: 'Argi utzi nahiko nuke...', esanahia: 'Quisiera dejar claro...', adibidez: 'Argi utzi nahiko nuke ez naizela ados.' },
  { id: '225', mota: 'Ziurtasuna', antolatzaileak: 'Argi dagoena da...', esanahia: 'Lo que está claro es...', adibidez: 'Argi dagoena da ez dugula nahikoa informazio.' },
  { id: '226', mota: 'Ziurtasuna', antolatzaileak: 'Inondik ere (ez)...', esanahia: 'Ni de lejos (no)...', adibidez: 'Inondik ere ez da horrela izan.' },
  { id: '227', mota: 'Ziurtasuna', antolatzaileak: 'Inondik inora ere (ez)...', esanahia: 'De ninguna manera...', adibidez: 'Inondik inora ere ezin da onartu.' },
  { id: '228', mota: 'Ziurtasuna', antolatzaileak: 'Inola ere (ez)...', esanahia: 'De ningún modo...', adibidez: 'Inola ere ez dugu onartuko.' },
  { id: '229', mota: 'Ziurtasuna', antolatzaileak: 'Zer esanik ez...', esanahia: 'Por supuesto...', adibidez: 'Zer esanik ez, parte hartzea oso handia izan da.' },
  { id: '230', mota: 'Ziurtasuna', antolatzaileak: 'Ziur...', esanahia: 'Seguro...', adibidez: 'Ziur gaude emaitza onak izango direla.' },
  { id: '231', mota: 'Ziurtasuna', antolatzaileak: 'Segur aski...', esanahia: 'Probablemente...', adibidez: 'Segur aski, eguraldi ona egingo du.' },
  { id: '232', mota: 'Ziurtasuna', antolatzaileak: 'Ziur asko...', esanahia: 'Muy probablemente...', adibidez: 'Ziur asko, ez da etorriko.' },
  { id: '233', mota: 'Ziurtasuna', antolatzaileak: 'Seguruenik (ziurrenik)...', esanahia: 'Seguramente...', adibidez: 'Seguruenik ez dugu berriro ikusiko.' },
  { id: '234', mota: 'Ziurtasuna', antolatzaileak: 'Seguruena (ziurrena)...', esanahia: 'Lo más seguro es que...', adibidez: 'Seguruena ez da hemen agertuko.' },
  { id: '235', mota: 'Ziurtasuna', antolatzaileak: 'Ezta pentsatu ere...', esanahia: 'Ni pensarlo siquiera...', adibidez: 'Ezta pentsatu ere horrelakorik egitea!' },
  { id: '236', mota: 'Agiantasuna', antolatzaileak: 'Agian...', esanahia: 'Quizás...', adibidez: 'Agian berandu etorriko da.' },
  { id: '237', mota: 'Agiantasuna', antolatzaileak: 'Beharbada...', esanahia: 'Tal vez...', adibidez: 'Beharbada ez du parte hartuko.' },
  { id: '238', mota: 'Agiantasuna', antolatzaileak: 'Apika...', esanahia: 'Puede que...', adibidez: 'Apika ez zen hura erruduna.' },
  { id: '239', mota: 'Agiantasuna', antolatzaileak: 'Menturaz...', esanahia: 'A lo mejor...', adibidez: 'Menturaz hobe da horrela uztea.' },
  { id: '240', mota: 'Agiantasuna', antolatzaileak: 'Ausaz...', esanahia: 'Por casualidad...', adibidez: 'Ausaz topatu genuen kalean.' },
  { id: '241', mota: 'Agiantasuna', antolatzaileak: 'Litekeena da...', esanahia: 'Es probable que...', adibidez: 'Litekeena da eguraldia aldatzea.' },
  { id: '242', mota: 'Egiantzekotasuna', antolatzaileak: 'Dirudienez...', esanahia: 'Por lo que parece...', adibidez: 'Dirudienez, ez da etorriko.' },
  { id: '243', mota: 'Egiantzekotasuna', antolatzaileak: 'Antza denez...', esanahia: 'Al parecer...', adibidez: 'Antza denez, ez du ezer esan nahi izan.' },
  { id: '244', mota: 'Egiantzekotasuna', antolatzaileak: '...antza', esanahia: '...al parecer', adibidez: 'Ez dago hemen, antza.' },
  { id: '245', mota: 'Egiantzekotasuna', antolatzaileak: 'Badirudi...', esanahia: 'Parece que...', adibidez: 'Badirudi ez dela ados egon.' },
  { id: '246', mota: 'Egiantzekotasuna', antolatzaileak: 'Itxuraz...', esanahia: 'Por lo visto...', adibidez: 'Itxuraz, ez da ezer gertatu.' },
  { id: '247', mota: 'Egiantzekotasuna', antolatzaileak: 'Itxura denez...', esanahia: 'Según parece...', adibidez: 'Itxura denez, dena ondo doa.' },
  { id: '248', mota: 'Egiantzekotasuna', antolatzaileak: 'Itxura guztien arabera...', esanahia: 'Según todas las apariencias...', adibidez: 'Itxura guztien arabera, galdu egingo dugu.' },
  { id: '249', mota: 'Egiantzekotasuna', antolatzaileak: 'Irudipena daukat...-la', esanahia: 'Tengo la impresión de que...', adibidez: 'Irudipena daukat gaizki ulertu dudala.' },
  { id: '250', mota: 'Egiantzekotasuna', antolatzaileak: 'Nonbait...', esanahia: 'Al parecer...', adibidez: 'Nonbait lanera joan da.' },
  { id: '251', mota: 'Egiantzekotasuna', antolatzaileak: 'Omen (ei)...', esanahia: 'Dicen que...', adibidez: 'Omen etorriko da bihar.' },
  { id: '252', mota: 'Egiantzekotasuna', antolatzaileak: 'Diotenez...', esanahia: 'Según dicen...', adibidez: 'Diotenez, eguraldia aldatuko da.' },
  { id: '253', mota: 'Egiantzekotasuna', antolatzaileak: 'Esaten dutenez...', esanahia: 'Según lo que dicen...', adibidez: 'Esaten dutenez, prezioak igoko dira.' },
  { id: '254', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Daitekeena da...', esanahia: 'Es posible que...', adibidez: 'Daitekeena da berandu iristea.' },
  { id: '255', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Litekeena da...', esanahia: 'Es probable que...', adibidez: 'Litekeena da euria egitea.' },
  { id: '256', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Baliteke...', esanahia: 'Puede que...', adibidez: 'Baliteke ez etortzea.' },
  { id: '257', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Gerta daitekeena da...', esanahia: 'Lo que puede suceder es...', adibidez: 'Gerta daitekeena da atzerapena egotea.' },
  { id: '258', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Gertagarriena (zera) da...', esanahia: 'Lo más probable es que...', adibidez: 'Gertagarriena da ez duela erantzungo.' },
  { id: '259', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Probableena (zera) da...', esanahia: 'La opción más probable es que...', adibidez: 'Probableena da arazo teknikoa izatea.' },
  { id: '260', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Kasurik onenean (ere)...', esanahia: 'En el mejor de los casos...', adibidez: 'Kasurik onenean, dena ondo aterako da.' },
  { id: '261', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Kasurik txarrenean (ere)...', esanahia: 'En el peor de los casos...', adibidez: 'Kasurik txarrenean, galdu egingo dugu.' },
  { id: '262', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Onenean ere...', esanahia: 'Incluso en el mejor caso...', adibidez: 'Onenean ere, arazo batzuk izango ditugu.' },
  { id: '263', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Txarrenean ere...', esanahia: 'Incluso en el peor caso...', adibidez: 'Txarrenean ere, saiatuko gara berriro.' },
  { id: '264', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Ahal dela...', esanahia: 'Siempre que sea posible...', adibidez: 'Ahal dela, goiz etorri.' },
  { id: '265', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Ahal den neurrian...', esanahia: 'En la medida de lo posible...', adibidez: 'Ahal den neurrian, saihestu behar da.' },
  { id: '266', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Segur aski...', esanahia: 'Probablemente...', adibidez: 'Segur aski, etxean izango da.' },
  { id: '267', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Ziur asko...', esanahia: 'Muy probablemente...', adibidez: 'Ziur asko, ez da etorriko.' },
  { id: '268', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Seguruenik...', esanahia: 'Seguramente...', adibidez: 'Seguruenik, erabakia hartua dago.' },
  { id: '269', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Segurunea...', esanahia: 'Lo más seguro es que...', adibidez: 'Segurunea, ez da iritsiko garaiz.' },
  { id: '270', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Ziurrenik...', esanahia: 'Seguramente...', adibidez: 'Ziurrenik, ez dugu berriro ikusiko.' },
  { id: '271', mota: 'Probabilitatea edo posibilitatea', antolatzaileak: 'Ziurrena...', esanahia: 'Lo más seguro es...', adibidez: 'Ziurrena ez da duela parte hartuko.' },
  { id: '272', mota: 'Beharrizana', antolatzaileak: 'Nahi eta nahi ez...', esanahia: 'Quieras o no...', adibidez: 'Nahi eta nahi ez, joan behar dugu.' },
  { id: '273', mota: 'Beharrizana', antolatzaileak: 'Nahitaez...', esanahia: 'Forzosamente...', adibidez: 'Nahitaez joan beharko du.' },
  { id: '274', mota: 'Beharrizana', antolatzaileak: 'Nahitaezkoa da...', esanahia: 'Es necesario...', adibidez: 'Nahitaezkoa da parte hartzea.' },
  { id: '275', mota: 'Beharrizana', antolatzaileak: 'Ezinbestean...', esanahia: 'Inevitablemente...', adibidez: 'Ezinbestean egin behar dugu.' },
  { id: '276', mota: 'Beharrizana', antolatzaileak: 'Ezinbestekoa da...', esanahia: 'Es imprescindible...', adibidez: 'Ezinbestekoa da arauak betetzea.' },
  { id: '277', mota: 'Beharrizana', antolatzaileak: 'Derrigorrez...', esanahia: 'Obligatoriamente...', adibidez: 'Derrigorrez aurkeztu behar da dokumentazioa.' },
  { id: '278', mota: 'Beharrizana', antolatzaileak: 'Baitezpadakoa da...', esanahia: 'Es absolutamente necesario...', adibidez: 'Baitezpadakoa da neurriak hartzea.' },
  { id: '279', mota: 'Beharrizana', antolatzaileak: 'Halabeharrez...', esanahia: 'Por necesidad...', adibidez: 'Halabeharrez onartu behar izan zuten.' },
  { id: '280', mota: 'Beharrizana', antolatzaileak: 'Beharrezkoa da...', esanahia: 'Es necesario...', adibidez: 'Beharrezkoa da prestakuntza egokia izatea.' },
  { id: '281', mota: 'Beharrizana', antolatzaileak: 'Egin behar dena da...', esanahia: 'Es lo que se debe hacer...', adibidez: 'Egin behar dena da ahalik eta hobekien jardutea.' },
  { id: '282', mota: 'Beharrizana', antolatzaileak: 'Kontuan hartu behar da...', esanahia: 'Hay que tenerlo en cuenta...', adibidez: 'Kontuan hartu behar da denboraz justu gabiltzala.' },
  { id: '283', mota: 'Beharrizana', antolatzaileak: 'Kontuan hartzekoa da...', esanahia: 'Es algo a tener en cuenta...', adibidez: 'Kontuan hartzekoa da adin-tartea ere.' },
  { id: '284', mota: 'Balorazioa', antolatzaileak: 'Zorionez...', esanahia: 'Afortunadamente...', adibidez: 'Zorionez, ez da ezer larririk gertatu.' },
  { id: '285', mota: 'Balorazioa', antolatzaileak: 'Zoritxarrez...', esanahia: 'Desgraciadamente...', adibidez: 'Zoritxarrez, berandu heldu ginen.' },
  { id: '286', mota: 'Balorazioa', antolatzaileak: 'Tamalez...', esanahia: 'Por desgracia...', adibidez: 'Tamalez, ez zen posible izan.' },
  { id: '287', mota: 'Balorazioa', antolatzaileak: 'Pozgarria da...', esanahia: 'Es una buena noticia...', adibidez: 'Pozgarria da jendeak parte hartu izana.' },
  { id: '288', mota: 'Balorazioa', antolatzaileak: 'Tamalgarri da...', esanahia: 'Es lamentable...', adibidez: 'Tamalgarri da hori entzutea.' },
  { id: '289', mota: 'Balorazioa', antolatzaileak: 'Kezkagarriena da...', esanahia: 'Lo más preocupante es...', adibidez: 'Kezkagarriena da egoera okertzen ari dela.' },
  { id: '290', mota: 'Balorazioa', antolatzaileak: 'Pena da...', esanahia: 'Es una pena...', adibidez: 'Pena da ez etortzea.' },
  { id: '291', mota: 'Balorazioa', antolatzaileak: 'Penagarria da...', esanahia: 'Es lamentable...', adibidez: 'Penagarria da horrela amaitzea.' },
  { id: '292', mota: 'Balorazioa', antolatzaileak: 'Oso interesgarria da...', esanahia: 'Es muy interesante...', adibidez: 'Oso interesgarria da zure proposamena.' },
  { id: '293', mota: 'Balorazioa', antolatzaileak: 'Onargarria ez dena da...', esanahia: 'Es inaceptable...', adibidez: 'Onargarria ez dena da jarrera hori.' },
  { id: '294', mota: 'Balorazioa', antolatzaileak: 'Ulergarria da...', esanahia: 'Es comprensible...', adibidez: 'Ulergarria da bere erantzuna.' },
  { id: '295', mota: 'Balorazioa', antolatzaileak: 'Ulertezina da...', esanahia: 'Es incomprensible...', adibidez: 'Ulertezina da bere jarrera.' },
  { id: '296', mota: 'Balorazioa', antolatzaileak: 'Eskerrak ...-n', esanahia: 'Menos mal que...', adibidez: 'Eskerrak garaiz iritsi ginen.' },
  { id: '297', mota: 'Balorazioa', antolatzaileak: 'Gaitz erdi ...-n', esanahia: 'Por suerte...', adibidez: 'Gaitz erdi euri pixka bat egitea.' },
  { id: '298', mota: 'Balorazioa', antolatzaileak: 'Beharrik ...-n', esanahia: 'Afortunadamente...', adibidez: 'Beharrik ez dela larria izan.' },
  { id: '299', mota: 'Balorazioa', antolatzaileak: 'Espero dezagun... -la', esanahia: 'Esperemos que...', adibidez: 'Espero dezagun dena ondo joatea.' },
  { id: '300', mota: 'Balorazioa', antolatzaileak: 'Espero dut... -la', esanahia: 'Espero que...', adibidez: 'Espero dut etorriko direla.' },
  { id: '301', mota: 'Balorazioa', antolatzaileak: 'Esperokoa da...', esanahia: 'Es lo esperado...', adibidez: 'Esperokoa da halako erreakzioa.' },
  { id: '302', mota: 'Balorazioa', antolatzaileak: 'Itxarotekoa da...', esanahia: 'Es esperable...', adibidez: 'Itxarotekoa da emaitza ona izatea.' },
  { id: '303', mota: 'Balorazioa', antolatzaileak: 'Beldur naiz ez ote...', esanahia: 'Temo que...', adibidez: 'Beldur naiz ez ote den beranduegi.' },
  { id: '304', mota: 'Balorazioa', antolatzaileak: 'Nahiago nuke...', esanahia: 'Preferiría...', adibidez: 'Nahiago nuke ezer ez esan.' },
  { id: '305', mota: 'Balorazioa', antolatzaileak: 'Amorrarazten nauena da...', esanahia: 'Lo que me enfada es...', adibidez: 'Amorrarazten nauena da ez dutela erantzuten.' },
  { id: '306', mota: 'Balorazioa', antolatzaileak: 'Txarrena da...', esanahia: 'Lo peor es...', adibidez: 'Txarrena da ez dela konpontzen.' },
  { id: '307', mota: 'Balorazioa', antolatzaileak: 'Kezkatzen nauena da...', esanahia: 'Lo que me preocupa es...', adibidez: 'Kezkatzen nauena da ez dela argi dagoenik.' },
  { id: '308', mota: 'Balorazioa', antolatzaileak: 'Egia izango ahal da...', esanahia: 'Ojalá sea cierto...', adibidez: 'Egia izango ahal da kontatu digutena.' },
  { id: '309', mota: 'Balorazioa', antolatzaileak: 'Egia balitz...', esanahia: 'Si fuera cierto...', adibidez: 'Egia balitz, ez litzateke txarra.' },
  { id: '310', mota: 'Balorazioa', antolatzaileak: 'Ez legoke txarto...', esanahia: 'No estaría mal...', adibidez: 'Ez legoke txarto gehiago informatzea.' },
  { id: '311', mota: 'Balorazioa', antolatzaileak: 'Ondo legoke...', esanahia: 'Estaría bien...', adibidez: 'Ondo legoke berriz elkartzea.' },
  { id: '312', mota: 'Balorazioa', antolatzaileak: 'Ondo etorriko litzaiguke...', esanahia: 'Nos vendría bien...', adibidez: 'Ondo etorriko litzaiguke laguntza pixka bat.' },
  { id: '313', mota: 'Balorazioa', antolatzaileak: 'Etsigarria da...', esanahia: 'Es desalentador...', adibidez: 'Etsigarria da emaitza hori ikustea.' },
  { id: '314', mota: 'Balorazioa', antolatzaileak: 'Zilegi da...', esanahia: 'Es legítimo...', adibidez: 'Zilegi da hala esatea.' },
  { id: '315', mota: 'Balorazioa', antolatzaileak: 'Bidezkoa da...', esanahia: 'Es justo...', adibidez: 'Bidezkoa da bere eskaera.' },
  { id: '316', mota: 'Balorazioa', antolatzaileak: 'Onartu ezin daitekeena...', esanahia: 'No se puede aceptar...', adibidez: 'Onartu ezin daitekeena da eraso hori.' },
  { id: '317', mota: 'Balorazioa', antolatzaileak: 'Legezkoa da...', esanahia: 'Es legal...', adibidez: 'Legezkoa da bere jarrera.' },
  { id: '318', mota: 'Aipamenak', antolatzaileak: 'Dirudienez...', esanahia: 'Por lo que parece...', adibidez: 'Dirudienez, ez da etorriko.' },
  { id: '319', mota: 'Aipamenak', antolatzaileak: 'Antza denez...', esanahia: 'Al parecer...', adibidez: 'Antza denez, ez da egia izan.' },
  { id: '320', mota: 'Aipamenak', antolatzaileak: 'Badirudi ...-la', esanahia: 'Parece que...', adibidez: 'Badirudi eguraldi txarra egingo duela.' },
  { id: '321', mota: 'Aipamenak', antolatzaileak: 'Irakurri dudanez...', esanahia: 'Según he leído...', adibidez: 'Irakurri dudanez, laster amaituko da.' },
  { id: '322', mota: 'Aipamenak', antolatzaileak: 'Entzun dudanez...', esanahia: 'Según he oído...', adibidez: 'Entzun dudanez, lan berria aurkitu du.' },
  { id: '323', mota: 'Aipamenak', antolatzaileak: 'Askoren ustez...', esanahia: 'Según muchos...', adibidez: 'Askoren ustez, ez da bidezkoa.' },
  { id: '324', mota: 'Aipamenak', antolatzaileak: 'Batzuen iritziz...', esanahia: 'Según algunos...', adibidez: 'Batzuen iritziz, aldaketak behar dira.' },
  { id: '325', mota: 'Aipamenak', antolatzaileak: 'Diotenez...', esanahia: 'Según dicen...', adibidez: 'Diotenez, ez dago konponbiderik.' },
  { id: '326', mota: 'Aipamenak', antolatzaileak: 'Komentatzen da...', esanahia: 'Se comenta que...', adibidez: 'Komentatzen da zuzendaritza aldatu egingo dela.' },
  { id: '327', mota: 'Aipamenak', antolatzaileak: 'Dakigunez...', esanahia: 'Según sabemos...', adibidez: 'Dakigunez, bilerak astelehenean izango dira.' },
  { id: '328', mota: 'Aipamenak', antolatzaileak: 'Ondo dakizunez...', esanahia: 'Como bien sabes...', adibidez: 'Ondo dakizunez, ez da erraza izan.' },
  { id: '329', mota: 'Aipamenak', antolatzaileak: 'Telebistan esan dutenez...', esanahia: 'Según dijeron en la televisión...', adibidez: 'Telebistan esan dutenez, prezioak igoko dira.' },
  { id: '330', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Gainera...', esanahia: 'Además...', adibidez: 'Gainera, ez dugu denborarik galdu behar.' },
  { id: '331', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Horrez gain...', esanahia: 'Además de eso...', adibidez: 'Horrez gain, beste aukera batzuk aztertu behar dira.' },
  { id: '332', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Horretaz gainera...', esanahia: 'Además de lo mencionado...', adibidez: 'Horretaz gainera, langileek ere protesta egin dute.' },
  { id: '333', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Ez hori bakarrik...', esanahia: 'No solo eso...', adibidez: 'Ez hori bakarrik, baizik eta gehiago ere.' },
  { id: '334', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Hori ez ezik... ere', esanahia: 'No solo eso... también', adibidez: 'Hori ez ezik, beste batzuk ere etorri dira.' },
  { id: '335', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Baita ere...', esanahia: 'También...', adibidez: 'Baita ere, gure laguntza jaso dute.' },
  { id: '336', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Are gehiago...', esanahia: 'Aún más...', adibidez: 'Are gehiago, ez dute inolako azalpenik eman.' },
  { id: '337', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Era berean...', esanahia: 'De la misma manera...', adibidez: 'Era berean, beste taldeak ere ados daude.' },
  { id: '338', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Modu berean...', esanahia: 'Igualmente...', adibidez: 'Modu berean jokatzen dute beti.' },
  { id: '339', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Gisa berean...', esanahia: 'De forma similar...', adibidez: 'Gisa berean azaldu da auzia beste kasuetan.' },
  { id: '340', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Halaber...', esanahia: 'Asimismo...', adibidez: 'Halaber, irakasleek bat egin dute eskaerarekin.' },
  { id: '341', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Orobat...', esanahia: 'Igualmente...', adibidez: 'Orobat, ikasleek erantzun ona eman dute.' },
  { id: '342', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Berebat...', esanahia: 'Del mismo modo...', adibidez: 'Berebat esan daiteke beste erakundeei buruz.' },
  { id: '343', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Bestalde...', esanahia: 'Por otra parte...', adibidez: 'Bestalde, ez da ahaztu behar araudia.' },
  { id: '344', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Beste alde batetik...', esanahia: 'Desde otro punto de vista...', adibidez: 'Beste alde batetik, ez dira ados agertu.' },
  { id: '345', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Bestetik...', esanahia: 'Por otro lado...', adibidez: 'Bestetik, ekarpen berriak jaso dira.' },
  { id: '346', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Kontuan hartzeko beste kontu bat...', esanahia: 'Otro aspecto a tener en cuenta es...', adibidez: 'Kontuan hartzeko beste kontu bat da finantziazioa.' },
  { id: '347', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Esan gabe doa...', esanahia: 'Ni que decir tiene...', adibidez: 'Esan gabe doa hori garrantzitsua dela.' },
  { id: '348', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Ezin daiteke ahaztu...', esanahia: 'No se puede olvidar...', adibidez: 'Ezin daiteke ahaztu lehenago gertatutakoa.' },
  { id: '349', mota: 'Ideia berriak txertatzeko', antolatzaileak: 'Beste puntu garrantzitsu bat...', esanahia: 'Otro punto importante es...', adibidez: 'Beste puntu garrantzitsu bat da denboraren kudeaketa.' },
  { id: '350', mota: 'Adibide-emaileak', antolatzaileak: 'Adibidez...', esanahia: 'Por ejemplo...', adibidez: 'Adibidez, horrelako egoerak gertatzen dira.' },
  { id: '351', mota: 'Adibide-emaileak', antolatzaileak: 'Esate baterako...', esanahia: 'Por poner un ejemplo...', adibidez: 'Esate baterako, irakasleek lan asko dute.' },
  { id: '352', mota: 'Adibide-emaileak', antolatzaileak: 'Esaterako...', esanahia: 'Por ejemplo...', adibidez: 'Esaterako, azken astean bi bilerak izan dira.' },
  { id: '353', mota: 'Adibide-emaileak', antolatzaileak: 'Kasurako...', esanahia: 'A modo de caso...', adibidez: 'Kasurako, ikasle hau kontuan hartu dezakegu.' },
  { id: '354', mota: 'Adibide-emaileak', antolatzaileak: 'Kasu...', esanahia: 'Caso...', adibidez: 'Kasu hau berezia da.' },
  { id: '355', mota: 'Adibide-emaileak', antolatzaileak: 'Adibide gisa...', esanahia: 'Como ejemplo...', adibidez: 'Adibide gisa, honako hau aipa dezakegu.' },
  { id: '356', mota: 'Adibide-emaileak', antolatzaileak: 'Hau da...', esanahia: 'Es decir...', adibidez: 'Hau da, ez dago aitzakiarik.' },
  { id: '357', mota: 'Adibide-emaileak', antolatzaileak: 'Hots...', esanahia: 'O sea...', adibidez: 'Hots, amaitu egin da epea.' },
  { id: '358', mota: 'Adibide-emaileak', antolatzaileak: 'Alegia...', esanahia: 'Es decir...', adibidez: 'Alegia, ezin da atzeratu gehiago.' },
  { id: '359', mota: 'Adibide-emaileak', antolatzaileak: 'Besteak beste...', esanahia: 'Entre otros...', adibidez: 'Besteak beste, hauek hartu dira kontuan.' },
  { id: '360', mota: 'Adibide-emaileak', antolatzaileak: 'Salbuespenak salbuespen...', esanahia: 'Con la excepción de las excepciones...', adibidez: 'Salbuespenak salbuespen, araua bete da.' },
  { id: '361', mota: 'Adibide-emaileak', antolatzaileak: 'Beste batzuen (askoren) artean...', esanahia: 'Entre otros muchos...', adibidez: 'Beste batzuen artean, hark nabarmendu zuen.' },
  { id: '362', mota: 'Adibide-emaileak', antolatzaileak: 'Hala nola...', esanahia: 'Tal como...', adibidez: 'Hala nola, artea eta musika.' },
  { id: '363', mota: 'Adibide-emaileak', antolatzaileak: 'Kasu bat aipatzeko...', esanahia: 'Para citar un caso...', adibidez: 'Kasu bat aipatzekotan, lan-munduan gertatzen da askotan.' },
  { id: '364', mota: 'Adibide-emaileak', antolatzaileak: 'Baten bat aipatzekotan...', esanahia: 'Si hubiera que mencionar uno...', adibidez: 'Baten bat aipatzekotan, gure inguruko kasuak dira egokienak.' },
  { id: '365', mota: 'Adibide-emaileak', antolatzaileak: 'Eman dezagun... / Demagun...', esanahia: 'Supongamos que...', adibidez: 'Eman dezagun egoera bat: etxean bakarrik dagoen umea.' },
  { id: '366', mota: 'Adibide-emaileak', antolatzaileak: 'Egin dezagun...', esanahia: 'Hagamos...', adibidez: 'Egin dezagun esperimentu bat.' },
  { id: '367', mota: 'Adibide-emaileak', antolatzaileak: 'Pentsa dezagun...', esanahia: 'Pensemos que...', adibidez: 'Pentsa dezagun ez dela erraza izango.' },
  { id: '368', mota: 'Adibide-emaileak', antolatzaileak: 'Imajina dezagun...', esanahia: 'Imaginemos que...', adibidez: 'Imajina dezagun irakaslea garela.' },
  { id: '369', mota: 'Adibide-emaileak', antolatzaileak: 'Nolabait esan...', esanahia: 'Por decirlo de algún modo...', adibidez: 'Nolabait esan, ez gaude prest.' },
  { id: '370', mota: 'Adibide-emaileak', antolatzaileak: 'Hona hemen adibide batzuk...', esanahia: 'Aquí van algunos ejemplos...', adibidez: 'Hona hemen adibide batzuk ikasteko.' },
  { id: '371', mota: 'Adibide-emaileak', antolatzaileak: 'Ikus dezagun zenbait adibide...', esanahia: 'Veamos algunos ejemplos...', adibidez: 'Ikus dezagun zenbait adibide argigarri.' },
  { id: '372', mota: 'Adibide-emaileak', antolatzaileak: 'Adibideotan ikus daitekeenez...', esanahia: 'Como puede verse en los ejemplos...', adibidez: 'Adibideotan ikus daitekeenez, erraza da ulertzea.' },
  { id: '373', mota: 'Adibide-emaileak', antolatzaileak: 'Konparazione...', esanahia: 'Por comparación...', adibidez: 'Konparazione, lehenago hobeto funtzionatzen zuen.' },
  { id: '374', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Horregatik...', esanahia: 'Por eso...', adibidez: 'Horregatik erabaki dut ez etortzea.' },
  { id: '375', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Arrazoi horregatik...', esanahia: 'Por esa razón...', adibidez: 'Arrazoi horregatik ez dugu onartu.' },
  { id: '376', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Hau dela eta...', esanahia: 'Debido a esto...', adibidez: 'Hau dela eta, aldaketak egingo dira.' },
  { id: '377', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Hori dela eta...', esanahia: 'Debido a eso...', adibidez: 'Hori dela eta, bilera deitu dugu.' },
  { id: '378', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Horren arabera...', esanahia: 'Según eso...', adibidez: 'Horren arabera jokatu behar da.' },
  { id: '379', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Gauzak horrela...', esanahia: 'Siendo así...', adibidez: 'Gauzak horrela, ez dago beste aukerarik.' },
  { id: '380', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Zeren eta...', esanahia: 'Ya que...', adibidez: 'Zeren eta denbora agortzen ari da.' },
  { id: '381', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Ezen...', esanahia: 'Porque...', adibidez: 'Ezen ez baitugu nahikoa informazio.' },
  { id: '382', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Ze...', esanahia: 'Porque...', adibidez: 'Ze ez dugu ulertu nahi izan.' },
  { id: '383', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Zergatik...', esanahia: '¿Por qué?', adibidez: 'Zergatik ez da etorri?' },
  { id: '384', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Horren kariaz...', esanahia: 'A causa de ello...', adibidez: 'Horren kariaz, salaketa jarri zuten.' },
  { id: '385', mota: 'Arrazoiak gehitzeko', antolatzaileak: 'Ildo beretik...', esanahia: 'En la misma línea...', adibidez: 'Ildo beretik, beste adibide bat aztertuko dugu.' },
  { id: '386', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Hala ere...', esanahia: 'Sin embargo...', adibidez: 'Hala ere, saiatu egingo gara.' },
  { id: '387', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Hala eta guztiz ere...', esanahia: 'Aun así...', adibidez: 'Hala eta guztiz ere, ez dugu amore emango.' },
  { id: '388', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Nolanahi ere...', esanahia: 'De todas formas...', adibidez: 'Nolanahi ere, emaitzak ez dira aldatu.' },
  { id: '389', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Edozelan ere...', esanahia: 'Sea como sea...', adibidez: 'Edozelan ere, egin behar da.' },
  { id: '390', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Edozertara ere...', esanahia: 'Aunque sea lo que sea...', adibidez: 'Edozertara ere prest gaude.' },
  { id: '391', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Edozein modutan...', esanahia: 'De cualquier manera...', adibidez: 'Edozein modutan saiatu dira.' },
  { id: '392', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Edozein moduz (ere)...', esanahia: 'Aunque sea de cualquier forma...', adibidez: 'Edozein moduz ere, ez dute lortu.' },
  { id: '393', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Dena dela (dena den)...', esanahia: 'En cualquier caso...', adibidez: 'Dena dela, onartu behar dugu.' },
  { id: '394', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Esanak esan...', esanahia: 'Digan lo que digan...', adibidez: 'Esanak esan, bera arrazoi zuen.' },
  { id: '395', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Eginak egin...', esanahia: 'Hagan lo que hagan...', adibidez: 'Eginak egin, ondorioak hor daude.' },
  { id: '396', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Nahiz eta...', esanahia: 'Aunque...', adibidez: 'Nahiz eta nekatuta egon, lan egin behar dugu.' },
  { id: '397', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: '... arren (ere)', esanahia: 'Aunque...', adibidez: 'Beldurra izan arren, aurrera egin zuen.' },
  { id: '398', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: '... bada ere', esanahia: 'Aunque...', adibidez: 'Hotza bada ere, irten egingo gara.' },
  { id: '399', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Horregatik ere...', esanahia: 'A pesar de eso...', adibidez: 'Horregatik ere, ez du funtzionatu.' },
  { id: '400', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Hori gorabehera...', esanahia: 'A pesar de ello...', adibidez: 'Hori gorabehera, ekintza positiboa izan da.' },
  { id: '401', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Esandako guztia gorabehera...', esanahia: 'A pesar de todo lo dicho...', adibidez: 'Esandako guztia gorabehera, ez dira ados jarri.' },
  { id: '402', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Esandako guztiagatik ere...', esanahia: 'Incluso por todo lo dicho...', adibidez: 'Esandako guztiagatik ere, ez dugu uko egingo.' },
  { id: '403', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Pentsa litekeenaren kontra...', esanahia: 'Contra lo que se pueda pensar...', adibidez: 'Pentsa litekeenaren kontra, emaitzak onak izan dira.' },
  { id: '404', mota: 'Arrazoiak kontrajartzeko', antolatzaileak: 'Espero litekeenaren kontra...', esanahia: 'Contra lo que se espera...', adibidez: 'Espero litekeenaren kontra, ez zuten parte hartu.' },
  { id: '405', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Ondorio gisa...', esanahia: 'Como conclusión...', adibidez: 'Ondorio gisa, esan daiteke lana ondo egin dela.' },
  { id: '406', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Ondorioz...', esanahia: 'En consecuencia...', adibidez: 'Ondorioz, ezin dugu jarraitu bezala.' },
  { id: '407', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Hemendik ondoriozta daiteke...', esanahia: 'De aquí se puede deducir...', adibidez: 'Hemendik ondoriozta daiteke aldaketa beharrezkoa dela.' },
  { id: '408', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Laburbilduz...', esanahia: 'En resumen...', adibidez: 'Laburbilduz, emaitzak onak izan dira.' },
  { id: '409', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Laburpen gisa...', esanahia: 'A modo de resumen...', adibidez: 'Laburpen gisa, nabarmendu behar da lana handia izan dela.' },
  { id: '410', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Hori (guztia) dela eta...', esanahia: 'Por todo ello...', adibidez: 'Hori guztia dela eta, erabakia hartu dugu.' },
  { id: '411', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Gauzak horrela...', esanahia: 'Siendo así...', adibidez: 'Gauzak horrela, ezin dugu atzera egin.' },
  { id: '412', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Arrazoi hauengatik (guztiengatik)...', esanahia: 'Por estas (todas) las razones...', adibidez: 'Arrazoi hauengatik ez dugu proiektua onartu.' },
  { id: '413', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Aurreko guztia kontuan hartuz...', esanahia: 'Teniendo en cuenta todo lo anterior...', adibidez: 'Aurreko guztia kontuan hartuz, hau da biderik onena.' },
  { id: '414', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Esandakoaren arabera...', esanahia: 'Según lo dicho...', adibidez: 'Esandakoaren arabera, ez da egokia.' },
  { id: '415', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Aztertutako datuen arabera...', esanahia: 'Según los datos analizados...', adibidez: 'Aztertutako datuen arabera, hobekuntzak behar dira.' },
  { id: '416', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Datu hauetan oinarrituz...', esanahia: 'Basándonos en estos datos...', adibidez: 'Datu hauetan oinarrituz, ondorio argiak ateratzen dira.' },
  { id: '417', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Beraz...', esanahia: 'Por lo tanto...', adibidez: 'Beraz, ezin dugu beste ezer egin.' },
  { id: '418', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Hortaz...', esanahia: 'Por consiguiente...', adibidez: 'Hortaz, proposamena baztertua izan da.' },
  { id: '419', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Azken batean...', esanahia: 'En definitiva...', adibidez: 'Azken batean, guztion onerako da.' },
  { id: '420', mota: 'Ondorioak ateratzeko', antolatzaileak: 'Azken finean...', esanahia: 'En última instancia...', adibidez: 'Azken finean, emaitza ez da txarra izan.' },
];

export const VIEW_ALL_TOP_LEVEL_CATEGORY = "DENAK IKUSI";

export const TOP_LEVEL_CATEGORIES_CONFIG: TopLevelCategory[] = [
  {
    name: "EGITURATZAILEAK",
    subCategories: ["Hasiera", "Jarraipena", "Amaiera", "Ordena"]
  },
  {
    name: "HIERARKIKOAK",
    subCategories: ["Lehentasuna", "Indartzea", "Orobatasuna", "Kontrastea"]
  },
  {
    name: "ERREFERENTZIALAK",
    subCategories: ["Denbora", "Lekua", "Anaforikoak", "Kataforikoak"]
  },
  {
    name: "MODALIZATZAILEAK",
    subCategories: [
      "Ustea edo iritzia", 
      "Ziurtasuna", 
      "Ziurtasunik eza", 
      "Agiantasuna", 
      "Egiantzekotasuna", 
      "Probabilitatea edo posibilitatea", 
      "Beharrizana", 
      "Balorazioa"
    ]
  },
  {
    name: "IRUZKINAK EGITEKOAK",
    subCategories: ["Aipamenak", "Ideia berriak txertatzeko", "Adibide-emaileak"]
  },
  {
    name: "ARGUDIOZKOAK",
    subCategories: ["Arrazoiak gehitzeko", "Arrazoiak kontrajartzeko", "Ondorioak ateratzeko"]
  },
  {
    name: VIEW_ALL_TOP_LEVEL_CATEGORY,
    subCategories: [] // Special case: no sub-categories, implies show all
  }
];

export const getTopLevelCategoryNames = (): string[] => {
  // Return in the order defined in TOP_LEVEL_CATEGORIES_CONFIG
  return TOP_LEVEL_CATEGORIES_CONFIG.map(tlc => tlc.name);
};

export const getSubCategoriesForTopLevel = (topLevelCategoryName: string): string[] => {
  const config = TOP_LEVEL_CATEGORIES_CONFIG.find(tlc => tlc.name === topLevelCategoryName);
  // Returns all defined subcategories for the top-level category, sorted.
  // The SubCategoryListScreen will handle displaying counts or disabled state.
  return config ? config.subCategories.slice().sort() : [];
};